# Numpy

NumPy is the basis of Pandas and many other packages. What makes NumPy such an incredible package is its data type (ndarray). ndarray stands for n-dimensional array, which basically looks like a Python list. However, it is a lot faster than a regular Python list. A Python list can contain different kinds of data types, such as integers, strings, Boolean, True, False and even lists. On the other hand, NumPy arrays can hold only one type of data, and therefore doesn't have to check the type of data type for every single element of the array when it is doing the computations. This feature makes NumPy a great tool for data science research and projects.

Here you have a collection of small exeercises that can help you to better understand the many functionalities of Numpy. Some of them have been covered in the theroy parts, some others have not. In this case, you will find some hints on the methods that you have yo use, but you should navigate through the NumPy documentation in order to understand how exactly use these methods.

You can find the NumPy documentation at [https://docs.scipy.org/doc/numpy/]()

## Numpy Arrays

#### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

#### 2. Print the numpy version

In [2]:
print('NumPy version:', np.__version__)

NumPy version: 1.16.4


#### 3. Create a one dimensional numpy array (you can choose the values)

In [3]:
one_d = np.array([1,2,3])
one_d

array([1, 2, 3])

#### 4. Create a one dimensional array of zeros (you can choose the size)

In [4]:
zeros = np.zeros (2)
zeros

array([0., 0.])

#### 5. Create a one dimensional array of ones (you can choose the size)

In [5]:
ones = np.ones ((2), dtype=int)
ones

array([1, 1])

#### 6. Create an array of 3 random integers between 1 and 10

In [6]:
random = np.random.randint(1,10, 3)
random

array([4, 3, 3])

#### 7. Create linearly spaced array
Hint: `np.linspace`

In [7]:
np.linspace (1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

#### 8. Create a 2-Dimensional array (you can choose the values)

In [8]:
two_dim = np.array([[2,3],[4,5]])
two_dim

array([[2, 3],
       [4, 5]])

#### 9. Create a 3x4 array with values between 0 and 1

In [9]:
tresx4 = np.random.random((3,4))
tresx4

array([[0.8410651 , 0.83340145, 0.41429763, 0.88073339],
       [0.54989696, 0.64691562, 0.11261636, 0.73356209],
       [0.84642462, 0.26456208, 0.19937195, 0.45993262]])

#### 10. Create a 2D array of random integers
Hint: `np.random.randint`

In [10]:
np.random.randint(5,20,(2,2))

array([[19, 13],
       [13, 13]])

#### 11. Create a 1D array and append a value to it
Hint: `np.append`

In [11]:
a = np.array([1,2])
b = np.append (a,3)
b

array([1, 2, 3])

#### 12. Print the shape and the number of dimensions of a 1D and a 2D array
Hint: `np.shape` and `np.ndim`

In [12]:
np.shape (b)

(3,)

In [13]:
np.ndim (b)

1

In [14]:
np.shape (two_dim)

(2, 2)

In [15]:
np.ndim(two_dim)

2

#### 13. Count the number of elements in the 1D and 2D arrays

In [16]:
b.size
np.size(b)

3

In [17]:
two_dim.size
np.size(two_dim)

4

#### 14. Get the first element of a 1D and 2D arrays, first accessing the array from the front, then accessing it from the back
Hint: negative index

In [18]:
print (b)
one_dim = b
one_dim[0]

[1 2 3]


1

In [19]:
one_dim[-3]

1

In [20]:
print (two_dim)

[[2 3]
 [4 5]]


In [21]:
two_dim[0,0]

2

In [22]:
two_dim[-2,-2]

2

#### 15. Get the last element of a 1D and 2D arrays, first accessing the array from the front, then accessing it from the back

In [23]:
print (one_dim)
one_dim[2]

[1 2 3]


3

In [24]:
one_dim[-1]

3

In [25]:
print (two_dim)
two_dim[1,1]

[[2 3]
 [4 5]]


5

In [26]:
two_dim[-1,-1]

5

#### 16. Get the first row of a 2D array

In [27]:
two_dim[0]

array([2, 3])

#### 17. Get the second column of a 2D array

In [28]:
two_dim[:,1]

array([3, 5])

#### Now consider the following array of integer from 1 to 10, which we will be using for the following exercises:

In [29]:
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 18. Get the first two elements of X 

In [30]:
X[0:2]

array([1, 2])

#### 19. Get the number 3,4 and 5 from X

In [31]:
X[2:5]

array([3, 4, 5])

#### 20. Get the odd numbers 

In [32]:
X[::2]   

array([1, 3, 5, 7, 9])

#### 21. Get the even numbers

In [33]:
X[1::2]

array([ 2,  4,  6,  8, 10])

#### Now consider the following 2D array:

In [34]:
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 22. Get the first and second row

In [35]:
Y[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

#### 23. Get the second and third column

In [36]:
Y[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

#### 24. Get the element of 5 and 6

In [37]:
Y[1,1:]

array([5, 6])

## Universal functions

We will now analyze some functions that allow fast computation in NumPy arrays.

We will be using the same array X created before:

In [38]:
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 25. Find the maximum element of X, the minimum element, and the sum of all elements in X
Hint: `np.max`, `np.min` and `np.sum`

In [39]:
np.max(X)

10

In [40]:
np.min(X)

1

In [41]:
np.sum(X)

55

#### 26. Get the mean and the median of the values in X
Hint: `np.mean` and `np.median`

In [42]:
np.mean(X)

5.5

In [43]:
np.median(X)

5.5

#### 27. Get the 4th power of each value in X
Hint: `np.power`

In [44]:
np.power(X,4)

array([    1,    16,    81,   256,   625,  1296,  2401,  4096,  6561,
       10000], dtype=int32)

#### 28. Get the sine of X
Hint: `np.sin`

In [45]:
np.sin(X)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

#### 29. Get the cosine of X
Hint: `np.cos`

In [46]:
np.cos(X)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

#### 30. Get the tangent of X
Hint: `np.tan`

In [47]:
np.tan(X)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

#### Now consider again the 2D array that we used before:

In [48]:
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 31. Multiply Y by 2

In [49]:
mult = Y*2
mult

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

#### 32. Split Y into 3 subarrays
Hint: `np.split`

In [50]:
np.split(Y,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

#### 33. Add 5 to each element (without using any other function)

In [51]:
Y+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### 34. Add 5 to each element
Hint: `np.add`

In [52]:
np.add(Y,5)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### Now consider the following Z array:

In [53]:
Z = np.arange(3)[:, np.newaxis]
Z

array([[0],
       [1],
       [2]])

#### 35. Multiply Y and Z
Hint: `np.multiply`

In [54]:
np.multiply (Y,Z)

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

## Sorting, comparing and masking

#### 36. Create an array of 10 elements between 1 and 5 and call it X

In [55]:
X = np.random.randint(1,5,10)
X

array([2, 2, 4, 3, 2, 2, 4, 1, 4, 4])

#### 37. Create a (3,3) size of array elements from 1 and 5 and call it Y

In [56]:
Y = np.random.randint (1,5,(3,3))
Y

array([[3, 1, 2],
       [1, 1, 4],
       [2, 4, 3]])

#### 38. Sort the elements in X
Hint: `np.sort`

In [57]:
np.sort(X)

array([1, 2, 2, 2, 2, 3, 4, 4, 4, 4])

#### 39. Sort values of Y along the x axis (rows)

In [58]:
np.sort(Y,axis=0)

array([[1, 1, 2],
       [2, 1, 3],
       [3, 4, 4]])

#### 39. Sort values of Y along the y axis (columns)

In [59]:
np.sort(Y, axis = 1)

array([[1, 2, 3],
       [1, 1, 4],
       [2, 3, 4]])

#### 40. Use masking feature to get the values of X greater than 3
Hint: `x > 3` will return a boolean mask of the values greater than 3

In [60]:
X[X>3]

array([4, 4, 4, 4])

#### 41. Use masking feature to get the values of X greater than 1 but smaller or equal than 3

In [61]:
X[(X>1) & (X<=3)]

array([2, 2, 3, 2, 2])

#### 42. Use masking feature to get the values of X that are even

In [62]:
X[(X%2==0)]

array([2, 2, 4, 2, 2, 4, 4, 4])

#### 43. Use masking feature to get the values of X that are odd

In [63]:
X[(X%2!=0)]

array([3, 1])

#### 44. Reshape X into a (2, 5) shaped array
Hint: `np.reshape`

In [64]:
d = X.reshape((2,5))
d

array([[2, 2, 4, 3, 2],
       [2, 4, 1, 4, 4]])

#### 45. Reshape X into a (5, 2) shaped array

In [65]:
e = X.reshape((5,2))
e

array([[2, 2],
       [4, 3],
       [2, 2],
       [4, 1],
       [4, 4]])

#### 46. Transpose X

In [66]:
np.transpose(X)

array([2, 2, 4, 3, 2, 2, 4, 1, 4, 4])

In [67]:
X.T

array([2, 2, 4, 3, 2, 2, 4, 1, 4, 4])

#### 47. Replace all odd numbers in X with -1 without changing X
Hint: `np.where`

In [71]:
print (X)
np.where (X%2==0, X , -1)

[2 2 4 3 2 2 4 1 4 4]


array([ 2,  2,  4, -1,  2,  2,  4, -1,  4,  4])

#### 48. Get the common items between a and b:
Hint: `np.intersect1d`

In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Desired output: array([2, 4])
np.intersect1d(a,b)


array([2, 4])

#### 49. From array a remove all items present in array b
Hint: `np.setdiff1d`

In [75]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

#### 50. Get the positions where elements of a and b match
Hint: `np.where`

In [76]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)